name: Bug report
description: Report a bug and upload your debug log file
title: "[BUG] "
labels: bug

body:
  - type: markdown
    attributes:
      value: |
        ## Describe the bug
        A clear and concise description of what the bug is.

  - type: textarea
    id: bug_description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Describe the steps to reproduce the bug."
      placeholder: "List the steps here..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Screenshots & Logfiles (Required)
        To help us understand and fix the issue, please upload relevant screenshots and the debug log. You can paste the log content below or manually attach the file by clicking on "Attach files by dragging & dropping, selecting or pasting them."

  - type: textarea
    id: debug_log
    attributes:
      label: "Debug Log"
      description: "Enable debug logging on instance of the adapter and post a debug log as .txt file from the start of the adapter up to two minutes after that."
      placeholder: "Enable debug logging on instance of the adapter and post a debug log as .txt file from the start of the adapter up to two minutes after that."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Versions
        Please provide the following version information.

  - type: input
    id: adapter_version
    attributes:
      label: "Adapter Version"
      description: "Version of the adapter"
      placeholder: "<adapter-version>"
    validations:
      required: true

  - type: input
    id: js_controller_version
    attributes:
      label: "JS-Controller Version"
      description: "Version of the JS-Controller (use `iobroker -v` to determine this)"
      placeholder: "<js-controller-version>"
    validations:
      required: true

  - type: input
    id: node_version
    attributes:
      label: "Node.js Version"
      description: "Version of Node.js (use `node -v` to determine this)"
      placeholder: "<node-version>"
    validations:
      required: true

  - type: input
    id: os_name
    attributes:
      label: "Operating System"
      description: "Name of the operating system"
      placeholder: "<os-name>"
    validations:
      required: true

  - type: input
    id: firmware_version
    attributes:
      label: "Firmware version of device"
      description: "Version of firmware of the device"
      placeholder: "Version of firmware of the device"
    validations:
      required: true
